//! What a frame costs on a real project tab.
//!
//! The markup is the application's own transcript, rendered by its own
//! components and captured from a real thread with every letter and digit
//! replaced, word lengths, line breaks and message lengths kept
//! (`fixtures/transcript.html`, regenerated by `TranscriptMarkup.test.tsx`).
//! The stylesheet is the 154KB bundle the application ships. Neither is
//! invented, which matters: an earlier version of this measurement used
//! hand-written bubbles and contained no `z-index` and no `position: fixed`
//! anywhere, so it could not have caught a paint regression in the very change
//! it was being used to justify.
//!
//! `REPEATS` mounts the captured pane several times over to reach the node
//! count the application reports for an open project tab, which is around
//! 4,350. Repeating real markup keeps the flex chains, the percentage caps and
//! the absolutely positioned chrome that a synthetic fixture flattens away.
//!
//!   cargo test -p blitz-tests --test transcript_frame_cost --features counters -- --nocapture

#![cfg(feature = "counters")]

use blitz_dom::layout_counters;
use blitz_dom::{DocumentConfig, QualName, ns};
use blitz_html::{HtmlDocument, HtmlProvider};
use blitz_traits::shell::{ColorScheme, Viewport};
use std::sync::Arc;

const WIDTH: u32 = 1344;
const HEIGHT: u32 = 900;
const REPEATS: usize = 18;

fn attr_name(local: &str) -> QualName {
    QualName {
        prefix: None,
        ns: ns!(),
        local: local.into(),
    }
}

fn project_tab() -> HtmlDocument {
    let css = include_str!("../fixtures/app.css");
    let markup = include_str!("../fixtures/transcript.html");
    let panes = markup.repeat(REPEATS);
    let html = format!(
        r#"<html><head><style>{css}</style></head>
           <body class="bg-base-100" style="margin:0">
             <div style="display:flex; flex-direction:column; width:{WIDTH}px; height:{HEIGHT}px;">
               {panes}
             </div>
           </body></html>"#
    );
    let mut doc = HtmlDocument::from_html(
        &html,
        DocumentConfig {
            viewport: Some(Viewport::new(WIDTH, HEIGHT, 1.0, ColorScheme::Dark)),
            html_parser_provider: Some(Arc::new(HtmlProvider) as _),
            ..Default::default()
        },
    );
    doc.resolve(0.0);
    doc
}

fn report(label: &str, total: usize) {
    let c = layout_counters::last();
    let hit_rate = if c.lookups == 0 {
        100.0
    } else {
        (c.hits as f64 / c.lookups as f64) * 100.0
    };
    println!(
        "{label:<18} computed={:<6} distinct={:<6} cleared={:<6} lookups={:<6} hits={:>5.1}%   of {total} nodes",
        c.computed, c.distinct, c.caches_cleared, c.lookups, hit_rate
    );
}

#[test]
fn a_frame_on_a_real_project_tab() {
    let mut doc = project_tab();
    let total = doc.tree().len();
    println!("\n== a real project tab, {total} nodes ==");

    doc.resolve(0.0);
    report("idle", total);
    let idle = layout_counters::last();

    // A streamed token: text appended to the last message body in the pane.
    let bodies = doc.query_selector_all("p").unwrap().to_vec();
    let last_body = *bodies.last().expect("the transcript has paragraphs");
    {
        let mut mutator = doc.mutate();
        let text = mutator.create_text_node("x");
        mutator.append_children(last_body, &[text]);
    }
    doc.resolve(0.0);
    report("streamed token", total);
    let token = layout_counters::last();

    // Hover: a class toggle on a button, which is what the chrome does
    // constantly and what item 9's narrowing was measured against.
    let button = doc.query_selector("button").unwrap().expect("no button");
    {
        let mut mutator = doc.mutate();
        mutator.set_attribute(button, attr_name("class"), "hovered");
    }
    doc.resolve(0.0);
    report("class toggle", total);

    println!();

    assert_eq!(
        idle.computed, 0,
        "an idle frame on a real tab recomputed {} nodes of {total}",
        idle.computed
    );
    assert!(
        token.distinct < 64,
        "one streamed token recomputed {} distinct nodes of {total}",
        token.distinct
    );
}
